wc:wc.c
	gcc -g -c wc.c
	gcc -o wc wc.o

getline:getline.c
	gcc -g -c getline.c
	gcc -o getline getline.o
getopt:getopt.c
	gcc -g -c getopt.c
	gcc -o getopt getopt.o
getopt_long:getopt_long.c
	gcc -g -c getopt_long.c
	gcc -o getopt_long getopt_long.o
