LIB=/Users/guosong/Desktop/Sina/Code/unix/lib

4-1:4-1.c
4-2:4-2.c
4-3:4-3.c
4-4:4-4.c
4-5:4-5.c
4-6:4-6.c
4-7:4-7.c
	gcc -g -c 4-7.c
	gcc -o 4-7 4-7.o -L$(LIB) -lapue
4-8:4-8.c
4-9:4-9.c
4-10:4-10.c
	gcc -g -c 4-10.c
	gcc -o 4-10 4-10.o -L$(LIB) -lapue

clean:
	rm -rf *.o
	rm -rf 4-1 4-2 4-3 4-4 4-5 4-6 4-7 \
		4-8 4-9 4-10
